version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NASA_API_KEY=${NASA_API_KEY}
      - EONET_BASE_URL=${EONET_BASE_URL:-https://eonet.gsfc.nasa.gov/api/v2.1}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
